/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { InvoiceItem, BudgetItem, UserProfile } from "./types.js";

// User database
export const SEED_USERS: UserProfile[] = [
  {
    id: "user_dir",
    name: "Rahul Sawant",
    email: "rahul@plantnutrition.in", // Bind to primary user for testing
    role: "Sales Director",
  },
  {
    id: "user_rm_west",
    name: "S. R. Patil",
    email: "srpatil@agroiq.com",
    role: "Regional Manager",
    region: "West",
  },
  {
    id: "user_rm_south",
    name: "K. Swamy",
    email: "kswamy@agroiq.com",
    role: "Regional Manager",
    region: "South",
  },
  {
    id: "user_rm_north",
    name: "R. K. Singh",
    email: "rksingh@agroiq.com",
    role: "Regional Manager",
    region: "North",
  },
  {
    id: "user_sp_west1",
    name: "V. R. Sharma",
    email: "vrsharma@agroiq.com",
    role: "Salesperson",
    region: "West",
    territory: "West-1",
    salespersonCode: "SP_W1",
    managerName: "S. R. Patil",
  },
  {
    id: "user_sp_west2",
    name: "A. P. Kulkarni",
    email: "apkulkarni@agroiq.com",
    role: "Salesperson",
    region: "West",
    territory: "West-2",
    salespersonCode: "SP_W2",
    managerName: "S. R. Patil",
  },
  {
    id: "user_sp_south1",
    name: "M. N. Rao",
    email: "mnrao@agroiq.com",
    role: "Salesperson",
    region: "South",
    territory: "South-1",
    salespersonCode: "SP_S1",
    managerName: "K. Swamy",
  },
  {
    id: "user_sp_south2",
    name: "S. Gopal",
    email: "sgopal@agroiq.com",
    role: "Salesperson",
    region: "South",
    territory: "South-2",
    salespersonCode: "SP_S2",
    managerName: "K. Swamy",
  },
  {
    id: "user_sp_north1",
    name: "Amit Verma",
    email: "averma@agroiq.com",
    role: "Salesperson",
    region: "North",
    territory: "North-1",
    salespersonCode: "SP_N1",
    managerName: "R. K. Singh",
  },
  {
    id: "user_admin",
    name: "System Admin",
    email: "admin@agroiq.com",
    role: "Admin",
  },
  {
    id: "user_dhanashree",
    name: "Dhanashree Agro",
    email: "dhanashree.agro@gmail.com",
    role: "Admin",
  },
  {
    id: "user_sushil_giri",
    name: "Sushil Giri",
    email: "sgiri@plantnutrition.in",
    role: "Regional Manager",
    region: "West",
    managerName: "Rahul Sawant"
  },
  {
    id: "user_gajanan_tale",
    name: "Gajanan Tale",
    email: "gtale@plantnutrition.in",
    role: "Regional Manager",
    region: "West",
    managerName: "Sushil Giri"
  },
  {
    id: "user_vishnu_bhagare",
    name: "Vishnu Bhagare",
    email: "vbhagre@plantnutrition.in",
    role: "Regional Manager",
    region: "West",
    managerName: "Sushil Giri"
  },
  {
    id: "user_rahul_borse",
    name: "Rahul Borse",
    email: "rborse@plantnutrition.in",
    role: "Salesperson",
    region: "West",
    territory: "West-3",
    managerName: "Gajanan Tale"
  },
  {
    id: "user_bhagwat_waghchaure",
    name: "Bhagwat Waghchaure",
    email: "bwaghachaure@plantnutrition.in",
    role: "Salesperson",
    region: "West",
    territory: "West-4",
    managerName: "Vishnu Bhagare"
  }
];

// Helper to generate Invoice Items representing the seed database
export const SEED_INVOICES: InvoiceItem[] = [
  // --- PREVIOUS FINANCIAL YEAR (1 March 2025 to 28 February 2026) ---
  // West Region (S. R. Patil - RM)
  // SP: V. R. Sharma (West-1)
  {
    id: "inv25_001",
    invoiceDate: "2025-03-12",
    invoiceNumber: "A/25/0012",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 120,
    unit: "KG",
    rate: 150,
    grossValue: 18000,
    discount: 900,
    netSalesValue: 17100,
  },
  {
    id: "inv25_002",
    invoiceDate: "2025-04-18",
    invoiceNumber: "A/25/0045",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 80,
    unit: "Litre",
    rate: 450,
    grossValue: 36000,
    discount: 1800,
    netSalesValue: 34200,
  },
  {
    id: "inv25_003",
    invoiceDate: "2025-05-10",
    invoiceNumber: "B/25/0022",
    company: "Company B",
    customerName: "Balaji Agro Services Satara",
    customerCode: "CUST002",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 500,
    unit: "Bags",
    rate: 300,
    grossValue: 150000,
    discount: 5000,
    netSalesValue: 145000,
  },
  {
    id: "inv25_004",
    invoiceDate: "2025-05-22",
    invoiceNumber: "A/25/0112",
    company: "Company A",
    customerName: "Krishna Agro Agency Nashik",
    customerCode: "CUST003",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "NanoStim Booster Plus",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 200,
    unit: "Litre",
    rate: 600,
    grossValue: 120000,
    discount: 12000,
    netSalesValue: 108000, // Will be "Lost" in 2026-27 (₹0)
  },
  {
    id: "inv25_005",
    invoiceDate: "2025-08-15",
    invoiceNumber: "A/25/0244",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "RhizoActive Soil Pro",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 300,
    unit: "KG",
    rate: 220,
    grossValue: 66000,
    discount: 3300,
    netSalesValue: 62700,
  },
  {
    id: "inv25_006",
    invoiceDate: "2025-10-05",
    invoiceNumber: "A/25/0430",
    company: "Company A",
    customerName: "Balaji Agro Services Satara",
    customerCode: "CUST002",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "Zinc Chelated 12% Max",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 400,
    unit: "KG",
    rate: 180,
    grossValue: 72000,
    discount: 3600,
    netSalesValue: 68400,
  },
  // SP: A. P. Kulkarni (West-2)
  {
    id: "inv25_007",
    invoiceDate: "2025-03-22",
    invoiceNumber: "A/25/0025",
    company: "Company A",
    customerName: "Jai Malhar Seeds Kolhapur",
    customerCode: "CUST004",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 150,
    unit: "Litre",
    rate: 450,
    grossValue: 67500,
    discount: 2500,
    netSalesValue: 65000,
  },
  {
    id: "inv25_008",
    invoiceDate: "2025-04-29",
    invoiceNumber: "B/25/0055",
    company: "Company B",
    customerName: "Jai Malhar Seeds Kolhapur",
    customerCode: "CUST004",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "MycoRoot Fungi",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 250,
    unit: "KG",
    rate: 280,
    grossValue: 70000,
    discount: 3000,
    netSalesValue: 67000,
  },
  {
    id: "inv25_009",
    invoiceDate: "2025-07-20",
    invoiceNumber: "B/25/0199",
    company: "Company B",
    customerName: "Saraswati Agro Solapur",
    customerCode: "CUST005",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "DAP Fert Quality Super",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 800,
    unit: "Bags",
    rate: 1200,
    grossValue: 960000,
    discount: 30000,
    netSalesValue: 930000,
  },
  {
    id: "inv25_010",
    invoiceDate: "2025-11-12",
    invoiceNumber: "A/25/0510",
    company: "Company A",
    customerName: "Saraswati Agro Solapur",
    customerCode: "CUST005",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "Zinc Chelated 12% Max",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 300,
    unit: "KG",
    rate: 180,
    grossValue: 54000,
    discount: 2000,
    netSalesValue: 52000,
  },

  // South Region (K. Swamy - RM)
  // SP: M. N. Rao (South-1)
  {
    id: "inv25_011",
    invoiceDate: "2025-03-15",
    invoiceNumber: "A/25/0019",
    company: "Company A",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 500,
    unit: "KG",
    rate: 150,
    grossValue: 75000,
    discount: 3750,
    netSalesValue: 71250,
  },
  {
    id: "inv25_012",
    invoiceDate: "2025-05-18",
    invoiceNumber: "B/25/0078",
    company: "Company B",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "DAP Fert Quality Super",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 1000,
    unit: "Bags",
    rate: 1200,
    grossValue: 1200000,
    discount: 50000,
    netSalesValue: 1150000,
  },
  {
    id: "inv25_013",
    invoiceDate: "2025-09-10",
    invoiceNumber: "A/25/0312",
    company: "Company A",
    customerName: "Venkateswara Seeds Nellore",
    customerCode: "CUST007",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "BactoProtect Shield",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 400,
    unit: "Litre",
    rate: 350,
    grossValue: 140000,
    discount: 7000,
    netSalesValue: 133000,
  },
  // SP: S. Gopal (South-2)
  {
    id: "inv25_014",
    invoiceDate: "2025-04-10",
    invoiceNumber: "A/25/0040",
    company: "Company A",
    customerName: "Kerala Agro Hub Trichur",
    customerCode: "CUST008",
    region: "South",
    state: "Kerala",
    territory: "South-2",
    salesperson: "S. Gopal",
    regionalManager: "K. Swamy",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 250,
    unit: "Litre",
    rate: 450,
    grossValue: 112500,
    discount: 5000,
    netSalesValue: 107500,
  },
  {
    id: "inv25_015",
    invoiceDate: "2025-08-22",
    invoiceNumber: "A/25/0288",
    company: "Company A",
    customerName: "Cauvery Fertilizers Salem",
    customerCode: "CUST009",
    region: "South",
    state: "Tamil Nadu",
    territory: "South-2",
    salesperson: "S. Gopal",
    regionalManager: "K. Swamy",
    productName: "NanoStim Booster Plus",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 300,
    unit: "Litre",
    rate: 600,
    grossValue: 180000,
    discount: 9000,
    netSalesValue: 171000,
  },

  // North Region (R. K. Singh - RM)
  // SP: Amit Verma (North-1)
  {
    id: "inv25_016",
    invoiceDate: "2025-04-12",
    invoiceNumber: "A/25/0038",
    company: "Company A",
    customerName: "Punjab Agro Dealers Bathinda",
    customerCode: "CUST010",
    region: "North",
    state: "Punjab",
    territory: "North-1",
    salesperson: "Amit Verma",
    regionalManager: "R. K. Singh",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 1200,
    unit: "Bags",
    rate: 300,
    grossValue: 360000,
    discount: 10000,
    netSalesValue: 350000,
  },
  {
    id: "inv25_017",
    invoiceDate: "2025-06-15",
    invoiceNumber: "B/25/0115",
    company: "Company B",
    customerName: "Haryana Beej Bhandar Karnal",
    customerCode: "CUST011",
    region: "North",
    state: "Haryana",
    territory: "North-1",
    salesperson: "Amit Verma",
    regionalManager: "R. K. Singh",
    productName: "RhizoActive Soil Pro",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 500,
    unit: "KG",
    rate: 220,
    grossValue: 110000,
    discount: 5500,
    netSalesValue: 104500,
  },


  // --- PAST YTD SPECIFIC RECORDS (1 March 2025 to 26 May 2025) ---
  // To verify comparative analysis
  {
    id: "inv25_ytd01",
    invoiceDate: "2025-03-20",
    invoiceNumber: "A/25Y/001",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 100,
    unit: "Litre",
    rate: 450,
    grossValue: 45000,
    discount: 2250,
    netSalesValue: 42750,
  },
  {
    id: "inv25_ytd02",
    invoiceDate: "2025-04-15",
    invoiceNumber: "B/25Y/005",
    company: "Company B",
    customerName: "Balaji Agro Services Satara",
    customerCode: "CUST002",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 1000,
    unit: "Bags",
    rate: 300,
    grossValue: 300000,
    discount: 9000,
    netSalesValue: 291000,
  },
  {
    id: "inv25_ytd03",
    invoiceDate: "2025-05-05",
    invoiceNumber: "A/25Y/012",
    company: "Company A",
    customerName: "Krishna Agro Agency Nashik",
    customerCode: "CUST003",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "NanoStim Booster Plus",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 150,
    unit: "Litre",
    rate: 600,
    grossValue: 90000,
    discount: 4500,
    netSalesValue: 85500,
  },
  {
    id: "inv25_ytd04",
    invoiceDate: "2025-03-25",
    invoiceNumber: "B/25Y/002",
    company: "Company B",
    customerName: "Jai Malhar Seeds Kolhapur",
    customerCode: "CUST004",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "MycoRoot Fungi",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 200,
    unit: "KG",
    rate: 280,
    grossValue: 56000,
    discount: 2000,
    netSalesValue: 54000,
  },
  {
    id: "inv25_ytd05",
    invoiceDate: "2025-05-20",
    invoiceNumber: "A/25Y/028",
    company: "Company A",
    customerName: "Saraswati Agro Solapur",
    customerCode: "CUST005",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 400,
    unit: "KG",
    rate: 150,
    grossValue: 60000,
    discount: 3000,
    netSalesValue: 57000,
  },
  {
    id: "inv25_ytd06",
    invoiceDate: "2025-04-11",
    invoiceNumber: "A/25Y/007",
    company: "Company A",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 600,
    unit: "KG",
    rate: 150,
    grossValue: 90000,
    discount: 4000,
    netSalesValue: 86000,
  },
  {
    id: "inv25_ytd07",
    invoiceDate: "2025-04-20",
    invoiceNumber: "B/25Y/009",
    company: "Company B",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "DAP Fert Quality Super",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 800,
    unit: "Bags",
    rate: 1200,
    grossValue: 960000,
    discount: 40000,
    netSalesValue: 920000,
  },
  {
    id: "inv25_ytd08",
    invoiceDate: "2025-05-12",
    invoiceNumber: "A/25Y/019",
    company: "Company A",
    customerName: "Cauvery Fertilizers Salem",
    customerCode: "CUST009",
    region: "South",
    state: "Tamil Nadu",
    territory: "South-2",
    salesperson: "S. Gopal",
    regionalManager: "K. Swamy",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 300,
    unit: "Litre",
    rate: 450,
    grossValue: 135000,
    discount: 5000,
    netSalesValue: 130000,
  },
  {
    id: "inv25_ytd09",
    invoiceDate: "2025-04-05",
    invoiceNumber: "A/25Y/003",
    company: "Company A",
    customerName: "Punjab Agro Dealers Bathinda",
    customerCode: "CUST010",
    region: "North",
    state: "Punjab",
    territory: "North-1",
    salesperson: "Amit Verma",
    regionalManager: "R. K. Singh",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 1500,
    unit: "Bags",
    rate: 300,
    grossValue: 450000,
    discount: 15000,
    netSalesValue: 435000,
  },


  // --- CURRENT FINANCIAL YEAR YTD (1 March 2026 to 26 May 2026) ---
  // West Region (RM: S. R. Patil)
  // SP: V. R. Sharma (West-1)
  {
    id: "inv26_001",
    invoiceDate: "2026-03-10",
    invoiceNumber: "A/26/0002",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 130, // Up from 100
    unit: "Litre",
    rate: 460, // Inflation adjustment
    grossValue: 59800,
    discount: 2500,
    netSalesValue: 57300, // YTD Group up from 42750
  },
  {
    id: "inv26_002",
    invoiceDate: "2026-04-12",
    invoiceNumber: "B/26/0014",
    company: "Company B",
    customerName: "Balaji Agro Services Satara",
    customerCode: "CUST002",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 950, // Down slightly
    unit: "Bags",
    rate: 310,
    grossValue: 294500,
    discount: 8500,
    netSalesValue: 286000, // Down slightly from 291000
  },
  {
    id: "inv26_003",
    invoiceDate: "2026-05-02",
    invoiceNumber: "A/26/0068",
    company: "Company A",
    customerName: "Mahalaxmi Fertilizers Pune",
    customerCode: "CUST001",
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "NanoStim Booster Plus",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 180,
    unit: "Litre",
    rate: 610,
    grossValue: 109800,
    discount: 4800,
    netSalesValue: 105000,
  },
  {
    id: "inv26_004",
    invoiceDate: "2026-05-15",
    invoiceNumber: "A/26/0099",
    company: "Company A",
    customerName: "Navnath Seeds & Fert Baramati",
    customerCode: "CUST101", // NEW CUSTOMER ADDED!
    region: "West",
    state: "Maharashtra",
    territory: "West-1",
    salesperson: "V. R. Sharma",
    regionalManager: "S. R. Patil",
    productName: "RhizoActive Soil Pro",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 250,
    unit: "KG",
    rate: 230,
    grossValue: 57500,
    discount: 2500,
    netSalesValue: 55000,
  },
  // SP: A. P. Kulkarni (West-2)
  {
    id: "inv26_005",
    invoiceDate: "2026-03-22",
    invoiceNumber: "B/26/0005",
    company: "Company B",
    customerName: "Jai Malhar Seeds Kolhapur",
    customerCode: "CUST004",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "MycoRoot Fungi",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 280, // Up from 200
    unit: "KG",
    rate: 290,
    grossValue: 81200,
    discount: 3200,
    netSalesValue: 78000, // Up from 54000
  },
  {
    id: "inv26_006",
    invoiceDate: "2026-05-18",
    invoiceNumber: "A/26/0115",
    company: "Company A",
    customerName: "Saraswati Agro Solapur",
    customerCode: "CUST005",
    region: "West",
    state: "Maharashtra",
    territory: "West-2",
    salesperson: "A. P. Kulkarni",
    regionalManager: "S. R. Patil",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 500, // Up from 400
    unit: "KG",
    rate: 155,
    grossValue: 77500,
    discount: 3500,
    netSalesValue: 74000, // Up from 57000
  },

  // South Region (RM: K. Swamy)
  // SP: M. N. Rao (South-1)
  {
    id: "inv26_007",
    invoiceDate: "2026-03-18",
    invoiceNumber: "A/26/0010",
    company: "Company A",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "AgroGrow Nutri Soluble (19:19:19)",
    productCategory: "Plant Nutrients",
    supplier: "Indo-German Organics",
    quantity: 650, // Up from 600
    unit: "KG",
    rate: 155,
    grossValue: 100750,
    discount: 4500,
    netSalesValue: 96250, // Up from 86000
  },
  {
    id: "inv26_008",
    invoiceDate: "2026-04-20",
    invoiceNumber: "B/26/0028",
    company: "Company B",
    customerName: "Sri Rama Agri Corp Guntur",
    customerCode: "CUST006",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "DAP Fert Quality Super",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 900, // Up from 800
    unit: "Bags",
    rate: 1250,
    grossValue: 1125000,
    discount: 45000,
    netSalesValue: 1080000, // Up from 920000
  },
  {
    id: "inv26_009",
    invoiceDate: "2026-05-10",
    invoiceNumber: "A/26/0074",
    company: "Company A",
    customerName: "Venkateswara Seeds Nellore",
    customerCode: "CUST007",
    region: "South",
    state: "Andhra Pradesh",
    territory: "South-1",
    salesperson: "M. N. Rao",
    regionalManager: "K. Swamy",
    productName: "BactoProtect Shield",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 300,
    unit: "Litre",
    rate: 360,
    grossValue: 108000,
    discount: 4000,
    netSalesValue: 104000, // New transaction during YTD period
  },
  // SP: S. Gopal (South-2)
  {
    id: "inv26_010",
    invoiceDate: "2026-03-25",
    invoiceNumber: "A/26/0013",
    company: "Company A",
    customerName: "Kerala Agro Hub Trichur",
    customerCode: "CUST008",
    region: "South",
    state: "Kerala",
    territory: "South-2",
    salesperson: "S. Gopal",
    regionalManager: "K. Swamy",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 260,
    unit: "Litre",
    rate: 460,
    grossValue: 119600,
    discount: 5000,
    netSalesValue: 114600,
  },
  {
    id: "inv26_011",
    invoiceDate: "2026-05-12",
    invoiceNumber: "A/26/0082",
    company: "Company A",
    customerName: "Cauvery Fertilizers Salem",
    customerCode: "CUST009",
    region: "South",
    state: "Tamil Nadu",
    territory: "South-2",
    salesperson: "S. Gopal",
    regionalManager: "K. Swamy",
    productName: "SugaMax Bio Enhancer",
    productCategory: "Biostimulants",
    supplier: "BioCore Solutions India",
    quantity: 280, // Down from 300
    unit: "Litre",
    rate: 460,
    grossValue: 128800,
    discount: 5800,
    netSalesValue: 123000, // Down from 130000 (Declining YTD product/customer)
  },

  // North Region (RM: R. K. Singh)
  // SP: Amit Verma (North-1)
  {
    id: "inv26_012",
    invoiceDate: "2026-04-05",
    invoiceNumber: "A/26/0018",
    company: "Company A",
    customerName: "Punjab Agro Dealers Bathinda",
    customerCode: "CUST010",
    region: "North",
    state: "Punjab",
    territory: "North-1",
    salesperson: "Amit Verma",
    regionalManager: "R. K. Singh",
    productName: "Urea Premium Shaktiman",
    productCategory: "Fertilizers",
    supplier: "GreenChem Fertilizers Corp",
    quantity: 1600, // Up from 1500
    unit: "Bags",
    rate: 310,
    grossValue: 496000,
    discount: 16000,
    netSalesValue: 480000, // Up from 435000
  },
  {
    id: "inv26_013",
    invoiceDate: "2026-05-24", // Right before current date 26 May
    invoiceNumber: "B/26/0105",
    company: "Company B",
    customerName: "Haryana Beej Bhandar Karnal",
    customerCode: "CUST011",
    region: "North",
    state: "Haryana",
    territory: "North-1",
    salesperson: "Amit Verma",
    regionalManager: "R. K. Singh",
    productName: "RhizoActive Soil Pro",
    productCategory: "Microbial products",
    supplier: "AgriTech Microbial Labs",
    quantity: 600,
    unit: "KG",
    rate: 230,
    grossValue: 138000,
    discount: 7000,
    netSalesValue: 131000,
  }
];

// Seed Budgets for current year (2026-27 / Financial Year 2026)
// Starting March 2026
export const SEED_BUDGETS: BudgetItem[] = [
  // Budget values designed for comparison with Actual YTD (Mar-May actuals)
  // V. R. Sharma - Actual YTD: SugaMax (57300), Urea (286000), NanoStim (105000), RhizoActive (55000) = Total ₹5.03L
  {
    id: "b_001",
    salesperson: "V. R. Sharma",
    product: "SugaMax Bio Enhancer",
    budgetQuantity: 200,
    budgetValue: 90000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_002",
    salesperson: "V. R. Sharma",
    product: "Urea Premium Shaktiman",
    budgetQuantity: 1000,
    budgetValue: 300000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_003",
    salesperson: "V. R. Sharma",
    product: "NanoStim Booster Plus",
    budgetQuantity: 200,
    budgetValue: 120000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  // A. P. Kulkarni - Actual YTD: MycoRoot (78000), AgroGrow (74000) = Total ₹1.52L
  {
    id: "b_004",
    salesperson: "A. P. Kulkarni",
    product: "MycoRoot Fungi",
    budgetQuantity: 300,
    budgetValue: 85000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_005",
    salesperson: "A. P. Kulkarni",
    product: "AgroGrow Nutri Soluble (19:19:19)",
    budgetQuantity: 600,
    budgetValue: 90000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  // M. N. Rao - Actual YTD: AgroGrow (96250), DAP (1080000), BactoProtect (104000) = Total ₹12.80L
  {
    id: "b_006",
    salesperson: "M. N. Rao",
    product: "DAP Fert Quality Super",
    budgetQuantity: 1000,
    budgetValue: 1200000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_007",
    salesperson: "M. N. Rao",
    product: "AgroGrow Nutri Soluble (19:19:19)",
    budgetQuantity: 800,
    budgetValue: 120000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_008",
    salesperson: "M. N. Rao",
    product: "BactoProtect Shield",
    budgetQuantity: 400,
    budgetValue: 140000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  // S. Gopal - Actual YTD: SugaMax (114600 + 123000) = Total ₹2.37L
  {
    id: "b_009",
    salesperson: "S. Gopal",
    product: "SugaMax Bio Enhancer",
    budgetQuantity: 600,
    budgetValue: 270000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  // Amit Verma - Actual YTD: Urea (480000), RhizoActive (131000) = Total ₹6.11L
  {
    id: "b_010",
    salesperson: "Amit Verma",
    product: "Urea Premium Shaktiman",
    budgetQuantity: 1500,
    budgetValue: 450000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  },
  {
    id: "b_011",
    salesperson: "Amit Verma",
    product: "RhizoActive Soil Pro",
    budgetQuantity: 500,
    budgetValue: 110000,
    month: "YTD (Mar-May)",
    financialYear: "2026-27",
  }
];

export const INITIAL_AUDIT_LOGS = [
  {
    timestamp: "2026-05-26T09:12:00Z",
    user: "System Setup",
    action: "Database Initialized",
    details: "Seed database pre-populated with standard multi-company agro transaction models.",
    status: "Success",
  },
  {
    timestamp: "2026-05-26T09:30:00Z",
    user: "Admin",
    action: "Excel ETL Model Verified",
    details: "Validated state standardisers and mapping indices for Company A and Company B.",
    status: "Success",
  }
];

export const INITIAL_EMAIL_LOGS = [
  {
    id: "em_log_001",
    dateSent: "2026-05-03T08:00:00Z",
    recipientEmail: "rahul@plantnutrition.in",
    recipientName: "Rahul Sawant",
    recipientRole: "Sales Director",
    subject: "Dhanashree AgriPulse: Monthly Executive Performance Report - April 2026",
    bodyPreview: "Company wide sales reached ₹22.4L in April 2026, driven by robust pre-monsoon fertilizer advance sales in South region.",
    status: "Delivered",
    attachments: ["Executive_Global_Summary_April.pdf"],
    triggerType: "Scheduled",
  },
  {
    id: "em_log_002",
    dateSent: "2026-05-03T08:15:00Z",
    recipientEmail: "srpatil@agroiq.com",
    recipientName: "S. R. Patil",
    recipientRole: "Regional Manager",
    subject: "Dhanashree AgriPulse: Regional Sales Performance Update - April 2026",
    bodyPreview: "West Region YTD Sales at ₹4.21L versus ₹3.88L last year. Biostimulants showed 12% rise in Satara territory.",
    status: "Delivered",
    attachments: ["West_Region_Details_April.pdf", "West_Subordinates_Performance.xlsx"],
    triggerType: "Scheduled",
  }
];
